### PR TITLE
added support for net45x

### PR DESCRIPTION
**Pull request by joonhwan**
Hi, 

I'd like to adapt your routemesiter in my legacy net 4.5.2 app which is currently not supported.
Please take a look if it is ok for me to use this library with this modification.
BTW, I do not know well about net core stuff. :-(

### CODE REVIEW

**Comment by danielwertheim** [comment]
Why wasn't it enough to just change the project file? Why was e.g. MessageRoutes changed?

**Comment by joonhwan** [comment]
oh. in my org, we still using c# 6.0 
You are right, I think that modification is unnecessary.

**Comment by danielwertheim** [comment]
You should be able to try this version: https://www.nuget.org/packages/Routemeister/3.0.0-pre12

It's a pre-release but nothing has changed except support for 4.5.1 as well.

**Comment by joonhwan** [comment]
> You should be able to try this version: https://www.nuget.org/packages/Routemeister/3.0.0-pre12
> 
> It's a pre-release but nothing has changed except support for 4.5.1 as well.

Thanks.

**Pull request closed without merging**
