### PR TITLE
Issue #6 add synchronous support

### PR DESCRIPTION
**Pull request by pwhe23**

### CODE REVIEW

**Comment by danielwertheim** [comment]
Nice and quick work! We celebrate midsummer here so might take until Monday until I have looked through it all.

**Comment by pwhe23** [comment]
No problem, have a great weekend!!

**Comment by pwhe23** [comment]
Let me know when it's up in Nuget as a prerelease, thanks!

**Comment by danielwertheim** [comment]
@pwhe23 It's out on NuGet as stable v2.1.0

Thanks for all the work

**Pull request merged**
